export enum ActionTypes {
  GET_SOURCES = 'GET_SOURCES',
  GET_SOURCES_SUCCESS = 'GET_SOURCES_SUCCESS',
  GET_SOURCES_ERROR = 'GET_SOURCES_ERROR',
  SET_SELECTE_SOURCE = 'SET_SELECTE_SOURCE',

  UPDATE_ARTICLE = 'UPDATE_ARTICLE',
  ADD_ARTICLE = 'ADD_ARTICLE',
  DELETE_ARTICLE = 'DELETE_ARTICLE',
  
  GET_ARTICLES = 'GET_ARTICLES',
  GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS',
  GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR',

  SET_SELECTED_BY_ME_OPTION = 'SET_SELECTED_BY_ME_OPTION',

  LOGIN_USER = 'LOGIN_USER'
}

