export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const GET_DATA_STARTED = 'GET_DATA_STARTED';

export const CHANGE_SEARCH_STRING = 'CHANGE_SEARCH_STRING';
export const CHANGE_SEARCH_FILTER = 'CHANGE_SEARCH_FILTER';
export const CHANGE_SORT_FILTER = 'CHANGE_SORT_FILTER';

export const SHOW_FILMS = 'SHOW_FILMS';
